### ISSUE TITLE
How can I help to keep the repo up to date? Angie 1.7.x released..

### ISSUE THREAD

**Issue by schories** [eilandert/deb.myguard.nl#14]
Hi Thijs,

searching the web I found your great repo. However, on a second look I've seen that since 2-3 months no major updates had been made regarding latest package versions. 

Meanwhile [Angie 1.7.x](https://en.angie.software/news/releases/angie-i-angie-pro-poluchili-obnovlenie-1-7-0/) has been released since about 1 month.

Do you still plan to continue operating this great repo at it's former pace?

How can I help? Seriously. It makes so much more sense to join forces rather than everyone maintaining their own building environment & builds.

Thank you so much!

Alexander

**Comment by eilandert** [comment]
aah I didn't see the Angie thing.  I think a patch failed otherwise it would have gone automaticly.  (I know last NGINX failed).

I have a couple of busy months now, if you are able to download the source package and create a updated one (probably a patch failing, and my first guess is the openssl patch from openresty) you are the man ;-)

**Comment by eilandert** [comment]
oh it was another patch, fixed

**Comment by schories** [comment]
Fantastic, let's do this - and thank you for the superfast fix!
